/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'folkol' at '10/9/16 1:06 AM' with Gradle 3.1
 *
 * @author folkol, @date 10/9/16 1:06 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
